[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphic-design-mcp"
version = "1.0.0"
description = "MCP Server for Graphic Design Analysis with OpenAI GPT-4o"
authors = [{name = "mcanince"}]
dependencies = [
    "openai>=1.0.0",
    "requests>=2.25.0"
]
requires-python = ">=3.8"

[project.scripts]
graphic-design-mcp = "mcp_graphic_design:main" 