[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graphic-design-mcp"
version = "0.1.0"
description = "Grafik tasarım analizi için MCP araçları - 4 tool tek dosyada"
authors = [
    {name = "mcanince", email = "mcanince@example.com"},
]
dependencies = [
    "fastmcp>=0.1.0",
    "openai>=1.0.0",
    "requests>=2.25.0",
    "beautifulsoup4",
    "lxml",
    "Pillow",
]
requires-python = ">=3.8"

[project.scripts]
graphic-design-mcp = "mcp_graphic_design:main" 